### ISSUE TITLE
Support for multi lang

### ISSUE THREAD

**Issue by riderx** [winkjs/wink-sentiment#26]
Do you have any plan to support multilang ?

**Comment by sanjayaksaxena** [comment]
Hello @riderx 

We have plans to add more languages — but on our new [`wink-nlp`](https://github.com/winkjs/wink-nlp) package. The code has been released along with [English language model (WIP)](https://github.com/winkjs/wink-eng-lite-model) and [documentation (WIP)](https://winkjs.org/wink-nlp/).

Best,
Sanjaya
